FROM kfx-launcher-qt-build-base

# MXE binary path
ENV PATH="${PATH}:/opt/mxe/usr/bin"

# MXE compiler target
ARG CROSS_TRIPLE="x86_64-w64-mingw32.static"

# Download MXE (M cross environment)
RUN cd /opt && \
    git clone https://github.com/mxe/mxe.git

# Build qt6-qtbase using mxe
RUN cd /opt/mxe && \
    make --jobs=$(nproc) JOBS=$(nproc) MXE_TARGETS=$CROSS_TRIPLE qt6-qtbase && \
    make clean-junk && \
    rm -rf pkg/* log/*

# Switch to the created user
#USER builduser
USER 1000